// <auto-generated />
using ATMService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATMService.Migrations
{
    [DbContext(typeof(ATMDbContext))]
    [Migration("20220123150038_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ATMService.DAL.Entities.MoneyDenomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("MoneyDenomination", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "1000",
                            Value = 1000
                        },
                        new
                        {
                            Id = 2,
                            Key = "2000",
                            Value = 2000
                        },
                        new
                        {
                            Id = 3,
                            Key = "5000",
                            Value = 5000
                        },
                        new
                        {
                            Id = 4,
                            Key = "10000",
                            Value = 10000
                        },
                        new
                        {
                            Id = 5,
                            Key = "20000",
                            Value = 20000
                        });
                });

            modelBuilder.Entity("ATMService.DAL.Entities.MoneyStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("MoneyDenominationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoneyDenominationId")
                        .IsUnique();

                    b.ToTable("MoneyStorage", "dbo");
                });

            modelBuilder.Entity("ATMService.DAL.Entities.MoneyStorage", b =>
                {
                    b.HasOne("ATMService.DAL.Entities.MoneyDenomination", "MoneyDenomination")
                        .WithMany()
                        .HasForeignKey("MoneyDenominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoneyDenomination");
                });
#pragma warning restore 612, 618
        }
    }
}
